// stageRegistry.js
// THE ONLY FILE TO TOUCH when adding, removing, or modifying stages.
// Adding a stage: add one object below. UI, backend, and DB pick it up automatically.
// Disabling a stage: set enabled: false

export const STAGES = [

  // ── PROJECT LEVEL — runs once per project ────────────────────────────────

  {
    id:           "competitor",
    level:        "project",
    enabled:      true,
    icon:         "🌐",
    label:        "Competitor Intel",
    color:        "#FF8800",
    description:  "Deep research · recent moves · gaps to exploit",
    useWebSearch: true,
    prompt: (ctx) => [
      "You are a senior competitive intelligence analyst. Research the competitive landscape for this product:",
      "",
      ctx.projectDescription || ctx.projectName,
      "",
      ctx.pseResults ? "GOOGLE SEARCH RESULTS (use these as primary sources):\n" + ctx.pseResults : "",
      "",
      "Provide a comprehensive, up-to-date competitive analysis. Focus heavily on RECENT developments (last 3-6 months).",
      "",
      "## TL;DR",
      "One paragraph executive summary of the competitive situation.",
      "",
      "## Market Overview",
      "Who are the key players? What is the current state of competition?",
      "",
      "## Key Competitors",
      "For each of the top 3-5 competitors: product overview, pricing, strengths, weaknesses, and target customer.",
      "",
      "## Recent Competitor Updates",
      "What have competitors shipped, announced, raised, or changed in the last 3-6 months? Be specific with dates.",
      "",
      "## Market Gaps & Opportunities",
      "What are competitors NOT doing well? Where is there whitespace?",
      "",
      "## Strategic Recommendations",
      "Given the above, what should this product prioritise to win?",
      "",
      "Never invent market share percentages. If data is unavailable, state 'Data Not Found.'",
      "Cite all sources with [Source URL]. Flag unverified claims as [Unverified].",
    ].join("\n"),
  },

  {
    id:           "market_analysis",
    level:        "project",
    enabled:      true,
    icon:         "📊",
    label:        "Market Analysis",
    color:        "#0066FF",
    description:  "Market size · trends · target segments · growth signals",
    useWebSearch: true,
    prompt: (ctx) => [
      "You are a market research analyst. Analyse the market for:",
      "",
      ctx.projectDescription || ctx.projectName,
      "",
      ctx.pseResults ? "SEARCH RESULTS:\n" + ctx.pseResults : "",
      "",
      "## TL;DR",
      "One paragraph summary of the market opportunity.",
      "",
      "## Market Size & Growth",
      "TAM, SAM, SOM with sources. YoY growth rate.",
      "",
      "## Target Segments",
      "Primary and secondary users. Demographics, jobs to be done.",
      "",
      "## Market Trends",
      "3-5 macro trends shaping this space in the next 12-24 months.",
      "",
      "## Buying Behaviour",
      "How do customers discover, evaluate, and buy? Who influences decisions?",
      "",
      "## Risks & Headwinds",
      "What could slow growth or threaten the opportunity?",
      "",
      "## Opportunity Summary",
      "One paragraph on why now is the right time.",
      "",
      "Never invent statistics. If data is unavailable, state 'Data Not Found.'",
      "Cite all sources with [Source URL].",
    ].join("\n"),
  },

  {
    id:          "feature_ideation",
    level:       "project",
    enabled:     true,
    icon:        "💡",
    label:       "Feature Ideation",
    color:       "#00AACC",
    description: "Winning features from competitive gaps · ranked by impact",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product strategist. Your job is to generate a prioritised list of features that would win in this market.",
      "",
      "PRODUCT: " + ctx.projectName,
      ctx.projectDescription ? "DESCRIPTION: " + ctx.projectDescription : "",
      ctx.competitor ? "COMPETITOR INTEL:\n" + (typeof ctx.competitor === "string" ? ctx.competitor.slice(0, 400) : JSON.stringify(ctx.competitor).slice(0, 400)) : "",
      ctx.market_analysis ? "MARKET ANALYSIS:\n" + (typeof ctx.market_analysis === "string" ? ctx.market_analysis.slice(0, 400) : JSON.stringify(ctx.market_analysis).slice(0, 400)) : "",
      ctx.interviewAnswers ? "ADDITIONAL CONTEXT FROM PRODUCT TEAM:\n" + ctx.interviewAnswers : "",
      "",
      "## TL;DR",
      "One paragraph: what category of product wins here and why.",
      "",
      "## Competitive Gap Features",
      "Features that directly exploit weaknesses or gaps in the competition.",
      "For each: Feature name · Why it wins · Which competitor it beats · Effort estimate (Low/Med/High)",
      "",
      "## Table Stakes Features",
      "Features that are expected by the market — must-haves to be taken seriously.",
      "For each: Feature name · Why it's non-negotiable · Current best-in-class example",
      "",
      "## Strategic Bets",
      "2-3 bold features that could redefine the category if they land.",
      "For each: Feature name · The bet · What has to be true for it to win · Risk level",
      "",
      "## Quick Wins",
      "Features that are low effort but high signal value — things that build trust fast.",
      "For each: Feature name · Why fast · Impact on user trust or retention",
      "",
      "## Features to Avoid",
      "Things competitors are doing that look attractive but are traps.",
      "For each: Feature · Why it's a trap · What to do instead",
      "",
      "## Recommended Build Order",
      "Given the above, what is the optimal sequence to build credibility and traction?",
      "Rank as: Phase 1 (0-3 months) · Phase 2 (3-6 months) · Phase 3 (6-12 months)",
    ].join("\n"),
  },

  {
    id:          "decision_log",
    level:       "project",
    enabled:     true,
    icon:        "📋",
    label:       "Decision Log",
    color:       "#8B00FF",
    description: "What we're building · what we're deferring · and why",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior PM capturing the reasoning behind product decisions. Your output will be used by developers and stakeholders to understand WHY the roadmap is built the way it is.",
      "",
      "PRODUCT: " + ctx.projectName,
      ctx.projectDescription ? "DESCRIPTION: " + ctx.projectDescription : "",
      ctx.feature_ideation ? "FEATURE IDEATION OUTPUT:\n" + (typeof ctx.feature_ideation === "string" ? ctx.feature_ideation.slice(0, 400) : JSON.stringify(ctx.feature_ideation).slice(0, 400)) : "",
      ctx.competitor ? "COMPETITOR CONTEXT:\n" + (typeof ctx.competitor === "string" ? ctx.competitor.slice(0, 300) : JSON.stringify(ctx.competitor).slice(0, 300)) : "",
      ctx.market_analysis ? "MARKET CONTEXT:\n" + (typeof ctx.market_analysis === "string" ? ctx.market_analysis.slice(0, 300) : JSON.stringify(ctx.market_analysis).slice(0, 300)) : "",
      ctx.interviewAnswers ? "DECISIONS FROM PRODUCT TEAM:\n" + ctx.interviewAnswers : "",
      "",
      "## TL;DR",
      "One paragraph: the core strategic bets being made and what's being explicitly traded off.",
      "",
      "## Included — What We're Building and Why",
      "For each included feature or capability:",
      "- Feature name",
      "- Business rationale: why this, why now",
      "- Customer signal or data point that supports this decision",
      "- What success looks like in 90 days",
      "",
      "## Deferred — What We're NOT Building Yet and Why",
      "For each deferred feature or capability:",
      "- Feature name",
      "- Why deferred: dependency / resourcing / strategic timing / not validated",
      "- What would need to be true to revisit this",
      "- Target review date or trigger event",
      "",
      "## Assumptions Being Made",
      "List the 3-5 key assumptions this decision set depends on.",
      "For each: the assumption · what happens if it's wrong · how we'd know early",
      "",
      "## Constraints Driving Decisions",
      "Technical, resource, market, or regulatory constraints that are shaping what's possible.",
      "",
      "## Open Decisions",
      "Things not yet decided that need resolution before development starts.",
      "For each: the decision · who owns it · deadline",
    ].join("\n"),
  },

  {
    id:          "roadmap",
    level:       "project",
    enabled:     true,
    icon:        "🗺️",
    label:       "Product Roadmap",
    color:       "#FF4444",
    description: "Phased delivery plan · milestones · dependencies",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product manager. Create a product roadmap grounded in the decisions already made.",
      "",
      "PRODUCT: " + ctx.projectName,
      ctx.projectDescription ? "DESCRIPTION: " + ctx.projectDescription : "",
      ctx.decision_log ? "DECISION LOG (what's in, what's out, and why):\n" + (typeof ctx.decision_log === "string" ? ctx.decision_log.slice(0, 400) : JSON.stringify(ctx.decision_log).slice(0, 400)) : "",
      ctx.feature_ideation ? "FEATURE IDEATION:\n" + (typeof ctx.feature_ideation === "string" ? ctx.feature_ideation.slice(0, 400) : JSON.stringify(ctx.feature_ideation).slice(0, 400)) : "",
      ctx.competitor ? "COMPETITOR CONTEXT:\n" + (typeof ctx.competitor === "string" ? ctx.competitor.slice(0, 300) : JSON.stringify(ctx.competitor).slice(0, 300)) : "",
      ctx.interviewAnswers ? "ADDITIONAL CONTEXT:\n" + ctx.interviewAnswers : "",
      "",
      "IMPORTANT: This roadmap must reflect the decisions in the Decision Log above.",
      "Do not invent new priorities. Phase the decided features into the timeline below.",
      "",
      "## Vision & North Star",
      "What does winning look like in 12 months?",
      "",
      "## Now (0-3 months)",
      "Features from Decision Log marked as included. For each: what, why now, success metric.",
      "",
      "## Next (3-6 months)",
      "Follow-on features and strategic bets. Dependencies on Now items.",
      "",
      "## Later (6-12 months)",
      "Deferred items with revised priority. What needs to be true to unlock these.",
      "",
      "## Key Milestones",
      "3-5 concrete milestones with dates and owners.",
      "",
      "## Dependencies & Risks",
      "What could derail this plan? What external dependencies exist?",
      "",
      "## Success Metrics",
      "How will we know this roadmap is working? 30/60/90 day indicators.",
    ].join("\n"),
  },

  {
    id:          "gtm",
    level:       "project",
    enabled:     true,
    icon:        "🚀",
    label:       "Go To Market",
    color:       "#00AA44",
    description: "Launch strategy · positioning · channels · pricing",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a GTM strategist. Build a GTM plan for:",
      "",
      "PRODUCT: " + ctx.projectName,
      ctx.projectDescription ? "DESCRIPTION: " + ctx.projectDescription : "",
      ctx.competitor ? "MARKET CONTEXT:\n" + (typeof ctx.competitor === "string" ? ctx.competitor.slice(0, 300) : JSON.stringify(ctx.competitor).slice(0, 300)) : "",
      ctx.market_analysis ? "MARKET ANALYSIS:\n" + (typeof ctx.market_analysis === "string" ? ctx.market_analysis.slice(0, 300) : JSON.stringify(ctx.market_analysis).slice(0, 300)) : "",
      ctx.roadmap ? "ROADMAP:\n" + (typeof ctx.roadmap === "string" ? ctx.roadmap.slice(0, 300) : JSON.stringify(ctx.roadmap).slice(0, 300)) : "",
      "",
      "## Positioning Statement",
      "For [target customer] who [problem], [product] is a [category] that [benefit]. Unlike [competitor], we [differentiator].",
      "",
      "## Target Customer",
      "ICP: company size, role, pain, trigger event.",
      "",
      "## Messaging Hierarchy",
      "Primary message. 3 supporting messages. Proof points.",
      "",
      "## Channel Strategy",
      "Ranked channels, why each, expected CAC.",
      "",
      "## Pricing & Packaging",
      "Recommended model and tiers with rationale.",
      "",
      "## Launch Plan",
      "Week by week for first 8 weeks.",
      "",
      "## Success Metrics",
      "30 / 60 / 90 day targets.",
    ].join("\n"),
  },

  // ── FEATURE LEVEL — runs per feature ────────────────────────────────────
  // ctx.constraints is automatically injected into every feature prompt

  {
    id:          "prd",
    level:       "feature",
    enabled:     true,
    icon:        "📄",
    label:       "PRD",
    color:       "#0066FF",
    description: "Full product requirements document",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product manager. Write a full PRD for this feature.",
      "",
      "PRODUCT: " + ctx.projectName,
      "FEATURE: " + ctx.featureName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.competitor ? "MARKET CONTEXT:\n" + (typeof ctx.competitor === "string" ? ctx.competitor.slice(0, 300) : JSON.stringify(ctx.competitor).slice(0, 300)) : "",
      ctx.decision_log ? "DECISION LOG:\n" + (typeof ctx.decision_log === "string" ? ctx.decision_log.slice(0, 300) : JSON.stringify(ctx.decision_log).slice(0, 300)) : "",
      "",
      "## TL;DR",
      "2-3 sentence executive summary of what this feature is and why it exists.",
      "",
      "## Problem Statement",
      "What problem does this solve? Who has it? Impact of not solving it?",
      "",
      "## Goals & Success Metrics",
      "3-5 measurable outcomes.",
      "",
      "## User Stories",
      "As a [user], I want to [action] so that [outcome]. Cover happy path and edge cases.",
      "",
      "## Functional Requirements",
      "Numbered list. Specific enough to build without questions.",
      "",
      "## Non-Functional Requirements",
      "Performance, security, accessibility, scalability.",
      "",
      "## Out of Scope",
      "What are we explicitly NOT building? Why?",
      "",
      "## Open Questions",
      "What needs to be decided? Who owns each?",
      "",
      "## Dependencies",
      "What does this depend on? What depends on this?",
      "",
      "## Friction Check",
      "3 reasons this feature might fail: one Technical Debt risk, one UX Friction risk, one Low Adoption risk.",
    ].join("\n"),
  },

  {
    id:          "architecture",
    level:       "feature",
    enabled:     true,
    icon:        "🏗️",
    label:       "Technical Architecture",
    color:       "#0099AA",
    description: "System design · data models · API contracts · tech decisions",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior software architect. Design the technical architecture for:",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.prd ? "PRD:\n" + (typeof ctx.prd === "string" ? ctx.prd.slice(0, 400) : JSON.stringify(ctx.prd).slice(0, 400)) : "",
      "",
      "## System Components",
      "Every component: name, responsibility, tech recommendation.",
      "",
      "## Data Models",
      "Key entities, fields, relationships.",
      "",
      "## API Design",
      "Key endpoints: method, path, request, response, auth.",
      "",
      "## Architecture Decisions",
      "3-5 decisions: what, why, trade-offs.",
      "",
      "## Scalability Considerations",
      "Load patterns, bottlenecks, how to scale.",
      "",
      "## Security Considerations",
      "Auth approach, data sensitivity, risks and mitigations.",
      "",
      "## Tech Stack Recommendation",
      "Recommended stack with justification.",
      "",
      "## Friction Check",
      "3 risks: one Technical Debt risk, one Integration risk, one Scalability risk.",
    ].join("\n"),
  },

  {
    id:          "flow",
    level:       "feature",
    enabled:     true,
    icon:        "🔀",
    label:       "High Level Flow",
    color:       "#AA00AA",
    description: "User journey · system interactions · edge cases · state transitions",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product and engineering lead. Map the complete flow for:",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.prd ? "PRD SUMMARY:\n" + (typeof ctx.prd === "string" ? ctx.prd.slice(0, 300) : JSON.stringify(ctx.prd).slice(0, 300)) : "",
      "",
      "## Happy Path Flow",
      "Step-by-step. What user does, what system does at each step.",
      "",
      "## System Interaction Flow",
      "Frontend -> Backend -> DB -> External services sequence.",
      "",
      "## Edge Cases & Alternate Flows",
      "Trigger, system handling, what user sees.",
      "",
      "## Error Handling Flow",
      "Network failures, validation errors, timeouts.",
      "",
      "## State Transitions",
      "Key states, what triggers them, what user sees.",
      "",
      "## Notifications & Side Effects",
      "Emails, push, webhooks, audit logs triggered.",
      "",
      "## Friction Check",
      "3 risks: one UX Friction risk, one Edge Case risk, one Integration risk.",
    ].join("\n"),
  },

  {
    id:          "ui_spec",
    level:       "feature",
    enabled:     true,
    icon:        "🎨",
    label:       "UI Spec",
    color:       "#E91E8C",
    description: "Screen inventory · components · interactions · accessibility",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product designer. Write a detailed UI specification for:",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.prd ? "PRD SUMMARY:\n" + (typeof ctx.prd === "string" ? ctx.prd.slice(0, 300) : JSON.stringify(ctx.prd).slice(0, 300)) : "",
      ctx.flow ? "USER FLOW:\n" + (typeof ctx.flow === "string" ? ctx.flow.slice(0, 400) : JSON.stringify(ctx.flow).slice(0, 400)) : "",
      "",
      "## Screen Inventory",
      "Every screen: name, purpose, entry points, exit points.",
      "",
      "## Component Specification",
      "Key components: name, purpose, states (default/hover/active/disabled/loading/error).",
      "",
      "## Interaction Patterns",
      "Key interactions: trigger, animation, user feedback.",
      "",
      "## Form Validation",
      "Every input: validation rules, error messages, when validation fires.",
      "",
      "## Empty & Loading States",
      "What user sees while loading. What they see with no data.",
      "",
      "## Responsive Behaviour",
      "How UI adapts across breakpoints.",
      "",
      "## Accessibility Requirements",
      "WCAG AA requirements. Keyboard nav, screen reader, colour contrast.",
      "",
      "## Copy & Microcopy",
      "Button labels, headings, helper text, error messages, success messages.",
      "",
      "## Friction Check",
      "3 risks: one UX Friction risk, one Accessibility risk, one Low Adoption risk.",
    ].join("\n"),
  },

  {
    id:          "diagram",
    level:       "feature",
    enabled:     true,
    icon:        "📐",
    label:       "Visual Diagram",
    color:       "#2E7D32",
    description: "Flow · sequence · ER diagrams — rendered visually",
    useWebSearch: false,
    renderer:    "mermaid",
    prompt: (ctx) => [
      "You are a software architect. Generate Mermaid diagram code for this feature.",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.architecture ? "ARCHITECTURE:\n" + (typeof ctx.architecture === "string" ? ctx.architecture.slice(0, 300) : JSON.stringify(ctx.architecture).slice(0, 300)) : "",
      ctx.flow ? "FLOW:\n" + (typeof ctx.flow === "string" ? ctx.flow.slice(0, 400) : JSON.stringify(ctx.flow).slice(0, 400)) : "",
      "",
      "Generate THREE Mermaid diagrams. Use this exact format:",
      "",
      "DIAGRAM: User Flow",
      "```mermaid",
      "flowchart TD",
      "    A[User opens feature] --> B{Authenticated?}",
      "    B -->|Yes| C[Show dashboard]",
      "    B -->|No| D[Redirect to login]",
      "```",
      "",
      "DIAGRAM: System Sequence",
      "```mermaid",
      "sequenceDiagram",
      "    participant U as User",
      "    participant F as Frontend",
      "    participant B as Backend",
      "    participant D as Database",
      "    U->>F: Action",
      "    F->>B: API call",
      "    B->>D: Query",
      "    D-->>B: Result",
      "    B-->>F: Response",
      "    F-->>U: Update UI",
      "```",
      "",
      "DIAGRAM: Data Model",
      "```mermaid",
      "erDiagram",
      "    ENTITY1 {",
      "        string id PK",
      "        string name",
      "    }",
      "    ENTITY2 {",
      "        string id PK",
      "        string entity1_id FK",
      "    }",
      "    ENTITY1 ||--o{ ENTITY2 : has",
      "```",
      "",
      "Adapt to accurately represent THIS specific feature.",
    ].join("\n"),
  },

  {
    id:          "review",
    level:       "feature",
    enabled:     true,
    icon:        "🔍",
    label:       "Spec Review",
    color:       "#FF4444",
    description: "Gap analysis · risks · ambiguities · what's missing",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior PM and tech lead doing a spec review. Be brutally honest.",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.constraints || "",
      ctx.prd ? "PRD:\n" + (typeof ctx.prd === "string" ? ctx.prd : JSON.stringify(ctx.prd)) : "No PRD yet.",
      ctx.architecture ? "ARCHITECTURE:\n" + (typeof ctx.architecture === "string" ? ctx.architecture.slice(0, 300) : JSON.stringify(ctx.architecture).slice(0, 300)) : "",
      ctx.flow ? "FLOW:\n" + (typeof ctx.flow === "string" ? ctx.flow.slice(0, 400) : JSON.stringify(ctx.flow).slice(0, 400)) : "",
      "",
      "## Critical Gaps",
      "What's missing that would block development?",
      "",
      "## Ambiguities",
      "What's unclear or could be interpreted multiple ways? Suggested resolutions.",
      "",
      "## Edge Cases Not Covered",
      "",
      "## Technical Risks",
      "What needs a spike or proof of concept?",
      "",
      "## Constraint Compliance",
      "Does the spec properly address all project constraints and compliance requirements?",
      "",
      "## Scope Concerns",
      "Too big for one sprint? What to cut for MVP?",
      "",
      "## Questions for Stakeholders",
      "What needs sign-off before development starts?",
      "",
      "## Overall Assessment",
      "Green / Amber / Red with one-paragraph summary.",
    ].join("\n"),
  },

  {
    id:          "tickets",
    level:       "feature",
    enabled:     true,
    icon:        "🎫",
    label:       "Tickets",
    color:       "#00AA44",
    description: "Jira-ready dev tickets with acceptance criteria",
    useWebSearch: false,
    renderer:    "tickets",
    prompt: (ctx) => [
      "You are a senior PM writing Jira tickets. Break down this feature into development tickets.",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.constraints || "",
      ctx.prd ? "PRD:\n" + (typeof ctx.prd === "string" ? ctx.prd.slice(0, 400) : JSON.stringify(ctx.prd).slice(0, 400)) : "",
      ctx.architecture ? "ARCHITECTURE:\n" + (typeof ctx.architecture === "string" ? ctx.architecture.slice(0, 400) : JSON.stringify(ctx.architecture).slice(0, 400)) : "",
      ctx.review ? "SPEC REVIEW:\n" + (typeof ctx.review === "string" ? ctx.review.slice(0, 300) : JSON.stringify(ctx.review).slice(0, 300)) : "",
      "",
      "Return ONLY a JSON array, no other text, no markdown fences. Each ticket:",
      '{"title":"Short imperative title","type":"feature"|"chore"|"bug","storyPoints":1|2|3|5|8,"description":"What to build and why","acceptanceCriteria":["criterion 1","criterion 2"]}',
      "",
      "Rules: No ticket over 8 points. Include setup/chore tickets. Acceptance criteria must be testable. 8-15 tickets total.",
      "Ensure all tickets respect the project constraints listed above.",
    ].join("\n"),
  },
];

export const PROJECT_STAGES  = STAGES.filter(s => s.level === "project" && s.enabled);
export const FEATURE_STAGES  = STAGES.filter(s => s.level === "feature" && s.enabled);
export const getStage        = (id) => STAGES.find(s => s.id === id);