// stageRegistry.js
// THE ONLY FILE TO TOUCH when adding, removing, or modifying stages.
// Adding a stage: add one object below. UI, backend, and DB pick it up automatically.
// Disabling a stage: set enabled: false

export const STAGES = [

  // PROJECT LEVEL — runs once per project

  {
    id:          "competitor",
    level:       "project",
    enabled:     true,
    icon:        "🌐",
    label:       "Competitor Intel",
    color:       "#FF8800",
    description: "Live web search · who's winning · gaps to exploit",
    useWebSearch: true,
    prompt: (ctx) => [
      "You are a product market research analyst. A product team is building:",
      "",
      ctx.projectDescription || ctx.projectName,
      "",
      "Search the web for the top 3-5 competitors or similar products.",
      "For each competitor: what they offer, strengths, weaknesses, pricing.",
      "",
      "## Market Overview",
      "## Key Competitors",
      "## Market Gaps & Opportunities",
      "## Latest Market Insights",
      "## Strategic Recommendations",
    ].join("\n"),
  },

  {
    id:          "market_analysis",
    level:       "project",
    enabled:     true,
    icon:        "📊",
    label:       "Market Analysis",
    color:       "#0066FF",
    description: "Market size · trends · target segments · growth signals",
    useWebSearch: true,
    prompt: (ctx) => [
      "You are a market research analyst. Analyse the market for:",
      "",
      ctx.projectDescription || ctx.projectName,
      "",
      "## Market Size & Growth",
      "TAM, SAM, SOM with sources. YoY growth rate.",
      "",
      "## Target Segments",
      "Primary and secondary users. Demographics, jobs to be done.",
      "",
      "## Market Trends",
      "3-5 macro trends shaping this space in the next 12-24 months.",
      "",
      "## Buying Behaviour",
      "How do customers discover, evaluate, and buy? Who influences decisions?",
      "",
      "## Risks & Headwinds",
      "What could slow growth or threaten the opportunity?",
      "",
      "## Opportunity Summary",
      "One paragraph on why now is the right time.",
    ].join("\n"),
  },

  {
    id:          "roadmap",
    level:       "project",
    enabled:     true,
    icon:        "🗺️",
    label:       "Product Roadmap",
    color:       "#8B00FF",
    description: "Phased delivery plan · milestones · dependencies",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product manager. Create a product roadmap for:",
      "",
      "PROJECT: " + ctx.projectName,
      ctx.projectDescription ? "DESCRIPTION: " + ctx.projectDescription : "",
      ctx.features?.length ? "FEATURES IN SCOPE:\n" + ctx.features.map(f => "- " + f.name + ": " + (f.description || "")).join("\n") : "",
      ctx.competitor ? "COMPETITOR CONTEXT:\n" + ctx.competitor.slice(0, 800) : "",
      "",
      "## Vision & North Star",
      "## Now (0-3 months)",
      "## Next (3-6 months)",
      "## Later (6-12 months)",
      "## Key Milestones",
      "## Dependencies & Risks",
      "## Success Metrics",
    ].join("\n"),
  },

  {
    id:          "gtm",
    level:       "project",
    enabled:     true,
    icon:        "🚀",
    label:       "Go To Market",
    color:       "#FF4444",
    description: "Launch strategy · positioning · channels · pricing",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a GTM strategist. Build a GTM plan for:",
      "",
      "PROJECT: " + ctx.projectName,
      ctx.projectDescription ? "DESCRIPTION: " + ctx.projectDescription : "",
      ctx.competitor ? "MARKET CONTEXT:\n" + ctx.competitor.slice(0, 600) : "",
      ctx.market_analysis ? "MARKET ANALYSIS:\n" + ctx.market_analysis.slice(0, 600) : "",
      "",
      "## Positioning Statement",
      "For [target customer] who [problem], [product] is a [category] that [benefit]. Unlike [competitor], we [differentiator].",
      "",
      "## Target Customer",
      "ICP: company size, role, pain, trigger event.",
      "",
      "## Messaging Hierarchy",
      "Primary message. 3 supporting messages. Proof points.",
      "",
      "## Channel Strategy",
      "Ranked channels, why each, expected CAC.",
      "",
      "## Pricing & Packaging",
      "Recommended model and tiers with rationale.",
      "",
      "## Launch Plan",
      "Week by week for first 8 weeks.",
      "",
      "## Success Metrics",
      "30 / 60 / 90 day targets.",
    ].join("\n"),
  },

  // FEATURE LEVEL — runs per feature
  // ctx.constraints is automatically injected into every feature prompt

  {
    id:          "prd",
    level:       "feature",
    enabled:     true,
    icon:        "📄",
    label:       "PRD",
    color:       "#0066FF",
    description: "Full product requirements document",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product manager. Write a full PRD for this feature.",
      "",
      "PRODUCT: " + ctx.projectName,
      "FEATURE: " + ctx.featureName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.competitor ? "MARKET CONTEXT:\n" + ctx.competitor.slice(0, 500) : "",
      "",
      "## Problem Statement",
      "What problem does this solve? Who has it? Impact of not solving it?",
      "",
      "## Goals & Success Metrics",
      "3-5 measurable outcomes.",
      "",
      "## User Stories",
      "As a [user], I want to [action] so that [outcome]. Cover happy path and edge cases.",
      "",
      "## Functional Requirements",
      "Numbered list. Specific enough to build without questions.",
      "",
      "## Non-Functional Requirements",
      "Performance, security, accessibility, scalability.",
      "",
      "## Out of Scope",
      "What are we explicitly NOT building? Why?",
      "",
      "## Open Questions",
      "What needs to be decided? Who owns each?",
      "",
      "## Dependencies",
      "What does this depend on? What depends on this?",
    ].join("\n"),
  },

  {
    id:          "architecture",
    level:       "feature",
    enabled:     true,
    icon:        "🏗️",
    label:       "Technical Architecture",
    color:       "#0099AA",
    description: "System design · data models · API contracts · tech decisions",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior software architect. Design the technical architecture for:",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.prd ? "PRD:\n" + ctx.prd.slice(0, 800) : "",
      "",
      "## System Components",
      "Every component: name, responsibility, tech recommendation.",
      "",
      "## Data Models",
      "Key entities, fields, relationships.",
      "",
      "## API Design",
      "Key endpoints: method, path, request, response, auth.",
      "",
      "## Architecture Decisions",
      "3-5 decisions: what, why, trade-offs.",
      "",
      "## Scalability Considerations",
      "Load patterns, bottlenecks, how to scale.",
      "",
      "## Security Considerations",
      "Auth approach, data sensitivity, risks and mitigations.",
      "",
      "## Tech Stack Recommendation",
      "Recommended stack with justification.",
    ].join("\n"),
  },

  {
    id:          "flow",
    level:       "feature",
    enabled:     true,
    icon:        "🔀",
    label:       "High Level Flow",
    color:       "#AA00AA",
    description: "User journey · system interactions · edge cases · state transitions",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product and engineering lead. Map the complete flow for:",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.prd ? "PRD SUMMARY:\n" + ctx.prd.slice(0, 600) : "",
      "",
      "## Happy Path Flow",
      "Step-by-step. What user does, what system does at each step.",
      "",
      "## System Interaction Flow",
      "Frontend -> Backend -> DB -> External services sequence.",
      "",
      "## Edge Cases & Alternate Flows",
      "Trigger, system handling, what user sees.",
      "",
      "## Error Handling Flow",
      "Network failures, validation errors, timeouts.",
      "",
      "## State Transitions",
      "Key states, what triggers them, what user sees.",
      "",
      "## Notifications & Side Effects",
      "Emails, push, webhooks, audit logs triggered.",
    ].join("\n"),
  },

  {
    id:          "ui_spec",
    level:       "feature",
    enabled:     true,
    icon:        "🎨",
    label:       "UI Spec",
    color:       "#E91E8C",
    description: "Screen inventory · components · interactions · accessibility",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior product designer. Write a detailed UI specification for:",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.constraints || "",
      ctx.prd ? "PRD SUMMARY:\n" + ctx.prd.slice(0, 600) : "",
      ctx.flow ? "USER FLOW:\n" + ctx.flow.slice(0, 400) : "",
      "",
      "## Screen Inventory",
      "Every screen: name, purpose, entry points, exit points.",
      "",
      "## Component Specification",
      "Key components: name, purpose, states (default/hover/active/disabled/loading/error).",
      "",
      "## Interaction Patterns",
      "Key interactions: trigger, animation, user feedback.",
      "",
      "## Form Validation",
      "Every input: validation rules, error messages, when validation fires.",
      "",
      "## Empty & Loading States",
      "What user sees while loading. What they see with no data.",
      "",
      "## Responsive Behaviour",
      "How UI adapts across breakpoints.",
      "",
      "## Accessibility Requirements",
      "WCAG AA requirements. Keyboard nav, screen reader, colour contrast.",
      "",
      "## Copy & Microcopy",
      "Button labels, headings, helper text, error messages, success messages.",
    ].join("\n"),
  },

  {
    id:          "diagram",
    level:       "feature",
    enabled:     true,
    icon:        "📐",
    label:       "Visual Diagram",
    color:       "#2E7D32",
    description: "Flow · sequence · ER diagrams — rendered visually",
    useWebSearch: false,
    renderer:    "mermaid",
    prompt: (ctx) => [
      "You are a software architect. Generate Mermaid diagram code for this feature.",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.featureDescription ? "DESCRIPTION: " + ctx.featureDescription : "",
      ctx.architecture ? "ARCHITECTURE:\n" + ctx.architecture.slice(0, 600) : "",
      ctx.flow ? "FLOW:\n" + ctx.flow.slice(0, 400) : "",
      "",
      "Generate THREE Mermaid diagrams. Use this exact format:",
      "",
      "DIAGRAM: User Flow",
      "```mermaid",
      "flowchart TD",
      "    A[User opens feature] --> B{Authenticated?}",
      "    B -->|Yes| C[Show dashboard]",
      "    B -->|No| D[Redirect to login]",
      "```",
      "",
      "DIAGRAM: System Sequence",
      "```mermaid",
      "sequenceDiagram",
      "    participant U as User",
      "    participant F as Frontend",
      "    participant B as Backend",
      "    participant D as Database",
      "    U->>F: Action",
      "    F->>B: API call",
      "    B->>D: Query",
      "    D-->>B: Result",
      "    B-->>F: Response",
      "    F-->>U: Update UI",
      "```",
      "",
      "DIAGRAM: Data Model",
      "```mermaid",
      "erDiagram",
      "    ENTITY1 {",
      "        string id PK",
      "        string name",
      "    }",
      "    ENTITY2 {",
      "        string id PK",
      "        string entity1_id FK",
      "    }",
      "    ENTITY1 ||--o{ ENTITY2 : has",
      "```",
      "",
      "Adapt to accurately represent THIS specific feature.",
    ].join("\n"),
  },

  {
    id:          "review",
    level:       "feature",
    enabled:     true,
    icon:        "🔍",
    label:       "Spec Review",
    color:       "#FF4444",
    description: "Gap analysis · risks · ambiguities · what's missing",
    useWebSearch: false,
    prompt: (ctx) => [
      "You are a senior PM and tech lead doing a spec review. Be brutally honest.",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.constraints || "",
      ctx.prd ? "PRD:\n" + ctx.prd : "No PRD yet.",
      ctx.architecture ? "ARCHITECTURE:\n" + ctx.architecture.slice(0, 600) : "",
      ctx.flow ? "FLOW:\n" + ctx.flow.slice(0, 400) : "",
      "",
      "## Critical Gaps",
      "What's missing that would block development?",
      "",
      "## Ambiguities",
      "What's unclear or could be interpreted multiple ways? Suggested resolutions.",
      "",
      "## Edge Cases Not Covered",
      "",
      "## Technical Risks",
      "What needs a spike or proof of concept?",
      "",
      "## Constraint Compliance",
      "Does the spec properly address all project constraints and compliance requirements?",
      "",
      "## Scope Concerns",
      "Too big for one sprint? What to cut for MVP?",
      "",
      "## Questions for Stakeholders",
      "What needs sign-off before development starts?",
      "",
      "## Overall Assessment",
      "Green / Amber / Red with one-paragraph summary.",
    ].join("\n"),
  },

  {
    id:          "tickets",
    level:       "feature",
    enabled:     true,
    icon:        "🎫",
    label:       "Tickets",
    color:       "#00AA44",
    description: "Jira-ready dev tickets with acceptance criteria",
    useWebSearch: false,
    renderer:    "tickets",
    prompt: (ctx) => [
      "You are a senior PM writing Jira tickets. Break down this feature into development tickets.",
      "",
      "FEATURE: " + ctx.featureName,
      "PRODUCT: " + ctx.projectName,
      ctx.constraints || "",
      ctx.prd ? "PRD:\n" + ctx.prd.slice(0, 800) : "",
      ctx.architecture ? "ARCHITECTURE:\n" + ctx.architecture.slice(0, 400) : "",
      ctx.review ? "SPEC REVIEW:\n" + ctx.review.slice(0, 300) : "",
      "",
      "Return ONLY a JSON array, no other text, no markdown fences. Each ticket:",
      '{"title":"Short imperative title","type":"feature"|"chore"|"bug","storyPoints":1|2|3|5|8,"description":"What to build and why","acceptanceCriteria":["criterion 1","criterion 2"]}',
      "",
      "Rules: No ticket over 8 points. Include setup/chore tickets. Acceptance criteria must be testable. 8-15 tickets total.",
      "Ensure all tickets respect the project constraints listed above.",
    ].join("\n"),
  },
];

export const PROJECT_STAGES = STAGES.filter(s => s.level === "project" && s.enabled);
export const FEATURE_STAGES = STAGES.filter(s => s.level === "feature" && s.enabled);
export const getStage = (id) => STAGES.find(s => s.id === id);
